### ISSUE TITLE
Débat OPIF - 1er jet

### ISSUE THREAD

**Issue by Elnadrin** [Insoumis/opif#2]
Le Grand Débat de TF1 ? Un départ en douceur... Tout en douc.... Oulah! Décidement, Fillon, fidèle à lui même, a une apathie contagieuse. Dans ses pensées, le représentant de la droite français n'entend pas son assistante qui l' houspille et lui demande d'entrer en scène. A raison, elle se situait à sa gauche et de plus ces derniers jours, ce vrai geek ne lit plus que ses sms.

Heureusement, MC Mélenchon va vite s'imposer comme le King de ce débat. Notre plus récent sondage, 323 000 votants, considère que Jean Luc devrait, à 74%, s'offrir le luxe de produire un album de rap en parallèle à sa campagne politique. Il est vrai que "Vos pudeurs de gazelles" ou "il faut bien qu'il y ait un débat au PS" sont des punchlines qui vont rester dans les Annales des débats politiques et faire d'excellents titres de track.

Mauvais départ du candidat Fillion, un Benoit Hamon un peu en retrait, il a fallu qu'il se frotte à l'étalon Macron pour lui redonner du poil de la bête. Et oui apparemment, la question du financement de la campagne du candidat d'En Marche lui provoque de l'urticaire. Toutefois ce n'est pas ce débat qui aura permis au candidat du PS de se démarquer. "Not my tempo" a-t-il crié à son coeur le lendemain. Et les sondages le confirment. Vote utile? 84% de nos 350 000 votants se disent favorable désormais au désistement d'Hamon en faveur de Mélenchon.

Quant à Marine Le Pen? Elle est tout aussi obnubilée par le mustang Emmanuel Macron. Elle est tellement convaincue de le rencontrer au deuxième tour qu'elle s'est même accordée avec Jean Luc Mélenchon à la fin du débat sur la question des handicapés. Franchement, rien ne lui résiste.Grand Corps Insoumi. Swag.

**Comment by Sramyaguchi** [comment]
Le Grand Débat de TF1 ? Un départ en douceur... Tout en douc.... Oulah ! Décidément, Fillon, fidèle à lui même, a une apathie contagieuse. Dans ses pensées, le représentant de la droite française n'entend pas son assistante qui l'houspille et lui demande d'entrer en scène. À raison, elle se situait à sa gauche et de plus, ces derniers jours, ce vrai geek ne lit plus que ses sms.

Heureusement, MC Mélenchon va vite s'imposer comme le King de ce débat. Notre plus récent sondage, 340 000 votants, considère que Jean Luc devrait, à 74%, s'offrir le luxe de produire un album de rap en parallèle à sa campagne politique. Il est vrai que "Vos pudeurs de gazelles" ou "il faut bien qu'il y ait un débat au PS" sont des punchlines qui vont rester dans les Annales des débats politiques et faire d'excellents titres d'un EP tant attendu.

Mauvais départ du candidat Fillon, un Benoit Hamon un peu en retrait, il a fallu qu'il se frotte à l'étalon Macron pour lui redonner du poil de la bête. Et oui apparemment, la question du financement de la campagne du candidat d'En Marche lui provoque de l'urticaire. Toutefois ce n'est pas ce débat qui aura permis au candidat du PS de se démarquer. "Not my tempo" a-t-il crié à son cœur (qu'il tente vaillamment de faire battre) le lendemain. Et les sondages le confirment (en douteriez-vous ?). Vote utile? 84% de nos 350 000 votants se disent favorables désormais au désistement d'Hamon en faveur de Mélenchon.

Quant à Marine Le Pen ? Rien. Ou presque. Elle est tout aussi obnubilée par le mustang Emmanuel Macron. Elle est tellement convaincue de le rencontrer au deuxième tour qu'elle s'est même accordée avec Jean-Luc Mélenchon à la fin du débat sur la question des handicapés. Franchement, rien ne lui résiste au beau Jean-Luc. Grand Corps Insoumis. Swag.
